# Generated by Django 4.0.4 on 2022-05-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_coursevi_podatoci_usercourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('courses', models.TextField()),
            ],
        ),
    ]
